import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";
import HomePage from "@/components/HomePage/HomePage";
import { getClient } from "@/components/Client/ApolloClient";
import { gql } from "@apollo/client";
const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps() {
  const client = getClient();
  const { data } = await client.query({
    query: gql`
      query GetArticles {
        products {
          data {
            attributes {
              headline
              subText
              description
              imageUrl
            }
          }
        }
      }
    `,
  });

  return {
    props: {
      data: data.products,
    },
  };
}

export default function Home({ data }: { data: any }) {
  console.log(data);
  return (
    <>
      <Head>
        <title>DOT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <HomePage data={data} />
    </>
  );
}
